<?php

namespace Database\Seeders;

use App\Models\Service;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Services extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $services = [
            ['name' => 'Troca de Óleo', 'amount' => 150.00],
            ['name' => 'Alinhamento de Direção', 'amount' => 100.00],
            ['name' => 'Balanceamento de Rodas', 'amount' => 80.00],
            ['name' => 'Lavagem Completa', 'amount' => 120.00],
            ['name' => 'Polimento de Pintura', 'amount' => 200.00],
            ['name' => 'Troca de Pneus', 'amount' => 600.00],
            ['name' => 'Revisão Completa', 'amount' => 300.00],
            ['name' => 'Troca de Filtro de Ar', 'amount' => 50.00],
            ['name' => 'Troca de Pastilhas de Freio', 'amount' => 250.00],
            ['name' => 'Serviço de Funilaria', 'amount' => 500.00],
            ['name' => 'Serviço de Pintura', 'amount' => 700.00],
            ['name' => 'Troca de Bateria', 'amount' => 400.00],
            ['name' => 'Reparo de Ar Condicionado', 'amount' => 350.00],
            ['name' => 'Troca de Velas', 'amount' => 120.00],
            ['name' => 'Serviço de Borracharia', 'amount' => 70.00],
            ['name' => 'Descarbonização do Motor', 'amount' => 450.00],
            ['name' => 'Troca de Fluido de Freio', 'amount' => 90.00],
            ['name' => 'Inspeção Veicular', 'amount' => 60.00],
            ['name' => 'Serviço de Suspensão', 'amount' => 300.00],
            ['name' => 'Troca de Correia Dentada', 'amount' => 500.00],
            ['name' => 'Limpeza de Bicos Injetores', 'amount' => 250.00],
            ['name' => 'Troca de Radiador', 'amount' => 600.00],
            ['name' => 'Serviço de Transmissão', 'amount' => 800.00],
            ['name' => 'Troca de Óleo de Câmbio', 'amount' => 200.00],
            ['name' => 'Reparo de Freios', 'amount' => 300.00],
            ['name' => 'Troca de Amortecedores', 'amount' => 400.00],
            ['name' => 'Serviço de Direção Hidráulica', 'amount' => 350.00],
            ['name' => 'Troca de Luzes', 'amount' => 50.00],
            ['name' => 'Reparo de Escapamento', 'amount' => 200.00],
            ['name' => 'Troca de Mangueiras', 'amount' => 100.00],
            ['name' => 'Serviço de Lavagem de Motor', 'amount' => 150.00],
            ['name' => 'Troca de Filtro de Combustível', 'amount' => 80.00],
            ['name' => 'Reparo de Vidros', 'amount' => 250.00],
            ['name' => 'Troca de Pneus de Estepe', 'amount' => 50.00],
            ['name' => 'Serviço de Polimento de Faróis', 'amount' => 100.00],
            ['name' => 'Troca de Óleo de Direção', 'amount' => 120.00],
            ['name' => 'Reparo de Suspensão', 'amount' => 300.00],
            ['name' => 'Serviço de Desentupimento', 'amount' => 200.00],
            ['name' => 'Troca de Filtro de Cabine', 'amount' => 70.00],
            ['name' => 'Reparo de Arrefecimento', 'amount' => 250.00],
            ['name' => 'Serviço de Lavagem a Seco', 'amount' => 180.00],
            ['name' => 'Troca de Óleo de Motor', 'amount' => 150.00],
            ['name' => 'Reparo de Transmissão', 'amount' => 800.00],
            ['name' => 'Troca de Filtro de Óleo', 'amount' => 60.00],
            ['name' => 'Serviço de Lavagem de Estofados', 'amount' => 250.00],
            ['name' => 'Troca de Juntas', 'amount' => 150.00],
            ['name' => 'Reparo de Sistema Elétrico', 'amount' => 300.00],
            ['name' => 'Serviço de Inspeção de Segurança', 'amount' => 100.00],
            ['name' => 'Troca de Sensor de Estacionamento', 'amount' => 200.00],
            ['name' => 'Reparo de Sistema de Freios ABS', 'amount' => 400.00],
            ['name' => 'Serviço de Alinhamento de Faróis', 'amount' => 80.00],
            ['name' => 'Troca de Bicos Injetores', 'amount' => 500.00],
            ['name' => 'Reparo de Sistema de Escape', 'amount' => 300.00],
            ['name' => 'Serviço de Limpeza de Ar Condicionado', 'amount' => 150.00],
            ['name' => 'Troca de Óleo de Diferencial', 'amount' => 200.00],
            ['name' => 'Reparo de Sistema de Direção', 'amount' => 350.00],
            ['name' => 'Serviço de Troca de Pneus de Verão', 'amount' => 600.00],
            ['name' => 'Troca de Óleo de Transmissão CVT', 'amount' => 250.00],
            ['name' => 'Reparo de Sistema de Suspensão Pneumática', 'amount' => 700.00],
            ['name' => 'Serviço de Inspeção de Emissões', 'amount' => 90.00],
            ['name' => 'Troca de Filtro de Ar do Motor', 'amount' => 50.00],
            ['name' => 'Reparo de Sistema de Injeção Eletrônica', 'amount' => 400.00],
            ['name' => 'Serviço de Troca de Pneus de Inverno', 'amount' => 600.00],
            ['name' => 'Troca de Óleo de Transmissão Manual', 'amount' => 200.00],
            ['name' => 'Reparo de Sistema de Arrefecimento', 'amount' => 300.00],
            ['name' => 'Serviço de Troca de Filtro de Combustível', 'amount' => 80.00],
            ['name' => 'Troca de Correia de Acessórios', 'amount' => 150.00],
            ['name' => 'Reparo de Sistema de Ventilação', 'amount' => 200.00],
            ['name' => 'Serviço de Troca de Óleo de Motor Diesel', 'amount' => 180.00],
            ['name' => 'Troca de Filtro de Óleo de Câmbio', 'amount' => 100.00],
            ['name' => 'Reparo de Sistema de Ignição', 'amount' => 250.00],
            ['name' => 'Serviço de Troca de Fluido de Transmissão', 'amount' => 200.00],
            ['name' => 'Troca de Juntas de Cabeçote', 'amount' => 600.00],
            ['name' => 'Reparo de Sistema de Direção Elétrica', 'amount' => 400.00],
            ['name' => 'Serviço de Troca de Óleo de Motor Flex', 'amount' => 150.00],
            ['name' => 'Troca de Filtro de Ar do Habitáculo', 'amount' => 70.00],
            ['name' => 'Reparo de Sistema de Câmbio Automático', 'amount' => 800.00],
            ['name' => 'Serviço de Inspeção de Pneus', 'amount' => 50.00],
            ['name' => 'Troca de Óleo de Motor a Gasolina', 'amount' => 150.00],
            ['name' => 'Reparo de Sistema de Suspensão Dianteira', 'amount' => 300.00],
            ['name' => 'Serviço de Troca de Fluido de Arrefecimento', 'amount' => 100.00],
            ['name' => 'Troca de Filtro de Combustível Diesel', 'amount' => 90.00],
            ['name' => 'Reparo de Sistema de Transmissão Manual', 'amount' => 500.00],
            ['name' => 'Serviço de Troca de Óleo de Motor Híbrido', 'amount' => 200.00],
            ['name' => 'Troca de Juntas de Válvula', 'amount' => 250.00],
            ['name' => 'Reparo de Sistema de Ar Condicionado Automotivo', 'amount' => 350.00],
            ['name' => 'Serviço de Inspeção de Freios', 'amount' => 80.00],
            ['name' => 'Troca de Filtro de Óleo de Motor', 'amount' => 60.00],
            ['name' => 'Reparo de Sistema de Direção Hidráulica', 'amount' => 300.00],
            ['name' => 'Serviço de Troca de Fluido de Direção', 'amount' => 100.00],
            ['name' => 'Troca de Correia de Distribuição', 'amount' => 500.00],
            ['name' => 'Reparo de Sistema de Ignição Eletrônica', 'amount' => 400.00],
            ['name' => 'Serviço de Troca de Óleo de Motor a Etanol', 'amount' => 150.00],
            ['name' => 'Troca de Filtro de Ar do Motor Diesel', 'amount' => 70.00],
            ['name' => 'Reparo de Sistema de Suspensão Traseira', 'amount' => 300.00],
            ['name' => 'Serviço de Troca de Fluido de Transmissão CVT', 'amount' => 250.00],
            ['name' => 'Troca de Juntas de Escape', 'amount' => 150.00],
            ['name' => 'Reparo de Sistema de Arrefecimento do Motor', 'amount' => 300.00],
            ['name' => 'Serviço de Inspeção de Segurança Veicular', 'amount' => 100.00],
            ['name' => 'Troca de Filtro de Óleo de Câmbio CVT', 'amount' => 80.00],
            ['name' => 'Reparo de Sistema de Suspensão de Câmbio', 'amount' => 400.00],
            ['name' => 'Serviço de Troca de Óleo de Motor a Gasóleo', 'amount' => 180.00],
            ['name' => 'Troca de Filtro de Ar do Motor Flex', 'amount' => 70.00],
            ['name' => 'Reparo de Sistema de Direção Assistida', 'amount' => 350.00],
            ['name' => 'Serviço de Troca de Fluido de Arrefecimento do Motor', 'amount' => 100.00],
            ['name' => 'Troca de Juntas de Válvula de Motor', 'amount' => 250.00],
            ['name' => 'Reparo de Sistema de Transmissão Automática', 'amount' => 800.00],
            ['name' => 'Serviço de Inspeção de Pneus e Rodas', 'amount' => 50.00],
            ['name' => 'Troca de Óleo de Motor a Gás', 'amount' => 150.00],
            ['name' => 'Reparo de Sistema de Suspensão de Direção', 'amount' => 300.00],
            ['name' => 'Serviço de Troca de Fluido de Direção Hidráulica', 'amount' => 100.00],
            ['name' => 'Troca de Correia de Acessórios de Motor', 'amount' => 150.00],
            ['name' => 'Reparo de Sistema de Ignição de Motor', 'amount' => 250.00],
            ['name' => 'Serviço de Troca de Óleo de Motor a Diesel', 'amount' => 180.00],
            ['name' => 'Troca de Filtro de Ar do Motor a Gasolina', 'amount' => 70.00],
            ['name' => 'Reparo de Sistema de Suspensão de Câmbio Automático', 'amount' => 400.00],
        ];

        foreach ($services as $service) {
            Service::create([
                'name' => $service['name'],
                'amount' => $service['amount'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }

    }
}
